name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/prepare-environment
      - name: Run tests
        run: cargo test --verbose

  publish:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Setup Environment
        uses: ./.github/actions/prepare-environment
      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          dry-run: ${{ github.event_name != 'push' }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true