name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare-environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v2
        name: Cache dependencies
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/master' }}

  test:
    runs-on: ubuntu-latest
    needs:
      - prepare-environment

    steps:
      - name: Run tests
        run: cargo test --verbose

  publish:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          dry-run: ${{ github.event_name != 'push' }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true